spring:
  datasource:
    url: jdbc:h2:mem:meu_banco
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    enabled: true
    console.path: /h2-console

  jpa:
    hibernate.ddl-auto: create-drop
    show-sql: true

  application:
    name: movies

server:
  port: 8080
